<?php
require_once 'propel/map/MapBuilder.php';
include_once 'creole/CreoleTypes.php';

/**
 *  This class was autogenerated by Propel on:
 *
 * [Fri Jun  4 20:26:28 2004]
 *
 * @package PEACH.Propel.map;
 */
class CategoryMapBuilder implements MapBuilder {

    /**
     * The name of this class
     */
    const CLASS_NAME = "PEACH.Propel.map.CategoryMapBuilder";
	
    /**
     * The database map.
     */
    private $dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public function isBuilt()
    {
        return ($this->dbMap !== null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public function getDatabaseMap()
    {
        return $this->dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
	 * @return void
     * @throws PropelException
     */
    public function doBuild()
    {
		$this->dbMap = Propel::getDatabaseMap("PEACH");
		
		$tMap = $this->dbMap->addTable("categories");
		$tMap->setPhpName("Category");
		
         
		$tMap->setUseIdGenerator(false);
		 
						
		 
		
		// Add columns to map
		$tMap->addPrimaryKey("ID", "id", "int", CreoleTypes::INTEGER);
		$tMap->addColumn("TITLE", "title", "string", CreoleTypes::VARCHAR, 60);
		$tMap->addColumn("DESCRIPTION", "description", "string", CreoleTypes::LONGVARCHAR, null);
		$tMap->addForeignKey("IMAGE_ID", "image_id", "int", CreoleTypes::INTEGER, "images" , "ID");
		$tMap->addForeignKey("PARENT_ID", "parent_id", "int", CreoleTypes::INTEGER, "categories" , "ID");
		$tMap->addColumn("CHILDREN", "children", "string", CreoleTypes::VARCHAR, 255);
				
    }
}
