<?php
require_once 'propel/om/Persistent.php';
require_once 'PEACH/Propel/om/BaseCategory.php';

/** 
 * The skeleton for this class was autogenerated by Propel  on:
 *
 * [Thu Jun  3 20:29:29 2004]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package PEACH.Propel 
 */
class Category extends BaseCategory implements Persistent {

    public function getEditLink()
    {
        return PEACH_Site::instance()->Link(
                'Edit',
                'Category',
                'editForm',
                array("id" => $this->getId())
                );

    }

    public function getDeleteLink()
    {
        return PEACH_Site::instance()->Link(
                'Delete',
                'Category',
                'delete',
                array("id" => $this->getId())
                );

    }

    public function getViewLink()
    {
        return PEACH_Site::instance()->Link(
                'View',
                'Category',
                'view',
                array("id" => $this->getId())
                );

    }

    public function saveForm($values)
    {
                $this->setTitle($values['title']);
                $this->setDescription($values['description']);
                if($values['image_id'] != 'none') {
                    $this->setImage_id($values['image_id']);
                } else {
                    $this->setImage_id(null);
                }
                if($values['parent_id'] != 'none') {
                    $this->setParent_id($values['parent_id']);
                }
                $this->setChildren($values['children']);
                $this->save();

    }


    public function displayImage()
    {
            require_once 'PEACH/Image.php';
            // note.. there is PEACH_Image and PROPEL..!!
            // later change PEACH_Image to propel
            if($this->getImage_id() != null) {
                $image = new PEACH_Image($this->getImage_id());
                return $image->toHtml();
            } else {
                return null;
            }
    }



}
