<?php
// The parent class
require_once 'PEACH/Propel/om/BasenewsPeer.php';

// The object class
include_once 'PEACH/Propel/news.php';

/** 
 * The skeleton for this class was autogenerated by Propel on:
 *
 * [Thu Jun  3 20:29:29 2004]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 *
 * @package PEACH.Propel 
 */
class newsPeer extends BasenewsPeer {

    public function doForm($obj = null)
    {
        // Create an HTML_QuickForm instance, and return to the current request uri
        $form = new HTML_QuickForm(__METHOD__, 'POST', $_SERVER['REQUEST_URI']);
        $form->addElement('header', 'edit', 'News');
	
	$form->addElement('text', 'subject', 'Subject');
	$form->addElement('textarea', 'summary', 'Summary'); 
	$form->addElement('textarea', 'body', 'Body');

        $c = new Criteria();
        $c->add(ImagePeer::FLAVOUR, serialize(array('thumb')));
        $c->addAscendingOrderByColumn(ImagePeer::LABEL);
        $results = ImagePeer::doSelect($c);

        $images = array();
        $images['none'] = "- no image -";
        // is this really necessary ?
        foreach($results as $row) {
            $images[$row->getId()] = $row->getLabel();
        }
        $form->addElement('select', 'image_id', 'Image', $images);


	$form->addElement('text', 'active', 'Active');
	$form->addElement('text', 'comments', 'Comments');
	$form->addElement('text', 'expiration', 'Expiration');
	$form->addElement('text', 'cat_id', 'Cat_id');
	/*
	Just for a reminder to add this
        $form->addRule('label', 'You must provide a title for this category', 'required');
        $form->addRule('description', 'You must provide a description for this category', 'required');
*/

        if (is_object($obj)) {
	    $defaultValues = array();
    $form->addElement('html', $obj->getThumb());
	            $defaultValues['subject'] = $obj->getSubject();

	            $defaultValues['summary'] = $obj->getSummary();

	            $defaultValues['body'] = $obj->getBody();

	            $defaultValues['image_id'] = $obj->getImage_id();

	            $defaultValues['active'] = $obj->getActive();

	            $defaultValues['anonymous'] = $obj->getAnonymous();

	            $defaultValues['userCreated'] = $obj->getUserCreated();

	            $defaultValues['userUpdated'] = $obj->getUserUpdated();

	            $defaultValues['dateCreated'] = $obj->getDateCreated();

	            $defaultValues['dateUpdated'] = $obj->getDateUpdated();

	            $defaultValues['poston'] = $obj->getPoston();

	            $defaultValues['expiration'] = $obj->getExpiration();

	            $defaultValues['cat_id'] = $obj->getCat_id();

	            // set the defaults 		
            $form->setDefaults($defaultValues);
        }

        $form->addElement('submit', 'submit', 'Continue');

        return $form;

    }

}
