<?php
require_once 'propel/om/Persistent.php';
require_once 'PEACH/Propel/om/Basenews.php';

/** 
 * The skeleton for this class was autogenerated by Propel  on:
 *
 * [Thu Jun  3 20:29:29 2004]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package PEACH.Propel 
 */
class news extends Basenews implements Persistent {

    public function getEditLink()
    {
        return PEACH_Site::instance()->Link(
                'Edit',
                'News',
                'editForm',
                array("id" => $this->getId())
                );

    }

    public function getDeleteLink()
    {
        return PEACH_Site::instance()->Link(
                'Delete',
                'News',
                'delete',
                array("id" => $this->getId())
                );

    }

    public function getViewLink()
    {
        return PEACH_Site::instance()->Link(
                'View',
                'News',
                'view',
                array("id" => $this->getId())
                );

    }



    function saveForm($values)
    {
        $this->setSubject(utf8_encode($values['subject']));
        $this->setSummary(utf8_encode($values['summary']));
        $this->setBody(utf8_encode($values['body']));
        $this->setImage_id($values['image_id']);

        if(!isset($this->approved)) {
            $this->setApproved(0);
        } else {
            $this->setApproved($values['approved']);
        }
        if(!isset($this->active)) {
            $this->setActive(0);
        } else {
            $this->setActive($values['active']);
        }
        if(!isset($this->anonymous)) {
            $this->setAnonymous(0);
        } else {
            $this->setAnonymous($values['anonymous']);
        }

        $now = date("Y-m-d H:i:s");
        if(!isset($this->userCreated)) {
            $this->setUserCreated($now);
        }
        $this->setUserUpdated($now);
        if(!isset($this->dateCreated)) {
            $this->setDateCreated($now);
        }
        $this->setDateUpdated($now);

        if(!isset($this->postOn)) {
            $this->setPoston($now);
        }
        $this->setExpiration($values['expiration']);
        $this->setCat_id($values['cat_id']);
        $this->save();

    }


    public function displayImage()
    {
        require_once 'PEACH/Image.php';
        // note.. there is PEACH_Image and PROPEL..!!
        // select the parent, we select only the thumbs in the form
        $child = new PEACH_Image($this->getImage_Id());
        $image = $child->getParent();
        return $image->toHtml();
    }

    public function getThumb()
    {
        require_once 'PEACH/Image.php';
        // note.. there is PEACH_Image and PROPEL..!!
        // select the parent, we select only the thumbs in the form
        $image = new PEACH_Image($this->getImage_Id());
        return $image->toHtml();

    }


}
